<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h2_homepage</name>
   <tag></tag>
   <elementGuidId>a9b94cfb-c8a8-4464-9417-089146a525a3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//h2[@id='banner']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#banner</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>11159571-cf81-41be-bbb1-ebb3bf5e2064</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>h2-section-5 justify-content-start</value>
      <webElementGuid>c96d40f7-09d2-44ad-99a6-ffda07364799</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>banner</value>
      <webElementGuid>ef572412-f94b-45df-bf2d-1f97b684f59f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Bulan Ramadan Banyak Diskon!</value>
      <webElementGuid>e2e85188-d857-4c59-942d-5b5617c9734f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;banner&quot;)</value>
      <webElementGuid>c055366e-8252-4ee9-82c0-b340a3110fc9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//h2[@id='banner']</value>
      <webElementGuid>889fd69b-93e1-407a-85fe-dde3505865d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/h2</value>
      <webElementGuid>5dfaf780-6a7a-4474-a48e-4c3bc7bbdb1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Masuk'])[1]/following::h2[1]</value>
      <webElementGuid>14c65014-0317-47a6-a738-6cc58ece6334</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Diskon Hingga 60%'])[1]/preceding::h2[1]</value>
      <webElementGuid>ab0e5fd4-5d72-45c8-9a4e-d3c910d05185</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Telusuri Kategori'])[1]/preceding::h2[1]</value>
      <webElementGuid>499477bd-0db8-472a-abaf-91e67b020c78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Bulan Ramadan Banyak Diskon!']/parent::*</value>
      <webElementGuid>ea0a14ab-5ffa-43ed-8303-93c14bee8427</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h2</value>
      <webElementGuid>845fc924-bc35-4a3b-bc5c-bcb41b012bdc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h2[@id = 'banner' and (text() = 'Bulan Ramadan Banyak Diskon!' or . = 'Bulan Ramadan Banyak Diskon!')]</value>
      <webElementGuid>740c2edb-e948-40ac-b94b-2b2cc2a08487</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
