<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>icon_lonceng</name>
   <tag></tag>
   <elementGuidId>84f22cc6-7062-454a-adf9-e382251abcd0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//button[@id='notification']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//button[@id='notification']</value>
      <webElementGuid>b3c97f4e-8275-46c6-892b-1ded84cd703a</webElementGuid>
   </webElementProperties>
</WebElementEntity>
