<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>field_handphone</name>
   <tag></tag>
   <elementGuidId>1bcbb4b8-bf0c-4de0-b2f1-e0a0f3b76a84</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>[placeholder='+62854263762']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>[placeholder='+62854263762']</value>
      <webElementGuid>6a2bcce0-4e4c-4507-ba8d-26728034f335</webElementGuid>
   </webElementProperties>
</WebElementEntity>
