<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>card_diminati</name>
   <tag></tag>
   <elementGuidId>58379ea1-c31b-4511-bbc9-d5c4299cf977</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>.content</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>content card</value>
      <webElementGuid>185dc42f-2a30-4f6e-9162-78c83e1f54da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>d9f947f8-a9ea-40c6-8dea-98265d9394e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>.content</value>
      <webElementGuid>113ed5fa-2874-4081-bbc1-6c62873b3eb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@class='content card']</value>
      <webElementGuid>281963d2-a72b-4330-99de-fac4e345ce0d</webElementGuid>
   </webElementProperties>
</WebElementEntity>
