<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>choose_kategori</name>
   <tag></tag>
   <elementGuidId>56b23c1e-6e68-4cc1-bbf7-fe69226a7b2e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;kategori&quot;]/option[2]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'kategori' and (text() = 'Pilih KategoriHobyKendaraanBajuElektronikKesehatan' or . = 'Pilih KategoriHobyKendaraanBajuElektronikKesehatan')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#kategori</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>fb47134d-e67f-4017-a5a4-7c0916417401</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>3156066d-3361-4c42-9b6f-e9bbad33d99a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>kategori</value>
      <webElementGuid>9291f610-948b-41f7-89b8-1b1181ec2464</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pilih KategoriHobyKendaraanBajuElektronikKesehatan</value>
      <webElementGuid>7f335b51-e9cd-4a8f-a984-2d6b6030d874</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;kategori&quot;)</value>
      <webElementGuid>2f500ef9-cc7a-42ee-bd2d-f9fd3c7277b0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='kategori']</value>
      <webElementGuid>8e4092b9-4eca-4388-9524-2ad5c25305f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/form/div[3]/select</value>
      <webElementGuid>cb84073a-9580-4490-ba8f-f9a9404611be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kategori'])[1]/following::select[1]</value>
      <webElementGuid>b8342094-d3d8-46fa-a51a-872ad1288810</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Harga Produk'])[1]/following::select[1]</value>
      <webElementGuid>617e2d6f-f07c-49b7-ae3a-b4f20152b297</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Deskripsi'])[1]/preceding::select[1]</value>
      <webElementGuid>30e8ef8e-269b-4118-9d5a-bc2dc645d3ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Foto Produk'])[1]/preceding::select[1]</value>
      <webElementGuid>3d09051d-6006-4b79-8d23-38d46b78cc03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//*[@id=&quot;kategori&quot;]/option[2]</value>
      <webElementGuid>af64a852-f879-4d6e-902c-bf9c36bb8cf3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'kategori' and (text() = 'Pilih KategoriHobyKendaraanBajuElektronikKesehatan' or . = 'Pilih KategoriHobyKendaraanBajuElektronikKesehatan')]</value>
      <webElementGuid>05ad9ae8-8575-4492-876d-e86368e417cd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
