<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_rectangle left</name>
   <tag></tag>
   <elementGuidId>e0577e61-b3ec-4714-b95a-9bb8292e868e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>78c4161d-2a9b-41eb-a031-5236d55ba2fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>./static/media/Rectangle-131.a85041256c34e39a64b1.png</value>
      <webElementGuid>728e2ffc-8177-4c5b-add9-037b31e7ccb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>11cab2d4-44cf-4272-8446-66dbfc43fdd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>8c0b7e23-82fa-49dd-a932-3e8589002a5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;App&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-6 d-none d-sm-block position-relative&quot;]/img[1]</value>
      <webElementGuid>cdc8a450-805c-4073-9a8b-0bbc1a44e411</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/img</value>
      <webElementGuid>117e9400-fad2-4471-bcf7-1d0c4c42829b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>6d4c5b6f-d537-4a3c-b9c2-a4dac9bb1ec7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = './static/media/Rectangle-131.a85041256c34e39a64b1.png']</value>
      <webElementGuid>ad6b7167-19ce-4453-9353-aee01cb295de</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
