<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>text_terjual</name>
   <tag></tag>
   <elementGuidId>543a1d76-eba9-4dd1-9147-5fc79c7e0d5b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//i[contains(.,'Terjual')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>&quot;link&quot; </value>
      <webElementGuid>6ca37a44-f85c-4fd4-957f-2b6537643169</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>1a6e5e3f-2a45-49ba-8d37-3e9f549bb5b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>button:nth-of-type(3) > [type='button']</value>
      <webElementGuid>fda39bf4-5de0-498d-a411-1173828b5cea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//i[contains(.,'Terjual')]</value>
      <webElementGuid>be3726ba-480f-455f-bd33-3fb4978756b5</webElementGuid>
   </webElementProperties>
</WebElementEntity>
