<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>feature_bid_or_buy_product</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>c16c4e35-701a-44d0-aa9b-14315408cdad</testSuiteGuid>
   <testCaseLink>
      <guid>c4d51e0a-2d6c-4114-b508-41238bf9ff92</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Step Definition/feature_bid_or_buy_product/BBP001 - Bid or buy product</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f56546bc-9b10-49fe-99cc-9dea389efbe9</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>755c766c-2646-4c14-a1b9-a0d52cfc312c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Step Definition/feature_bid_or_buy_product/BBPHelper for change status</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7ed8039b-4654-470f-a6c4-fa9266bc9479</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
