<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>feature_accept_bid</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>8c9bf414-9464-4c06-9916-f514cf3d1b90</testSuiteGuid>
   <testCaseLink>
      <guid>1c227411-5f0b-4ba0-8534-03c173ac54ea</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Step Definition/feature_bid_or_buy_product/BBPHelper for accept bid</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>74f4c204-6cd2-46af-8df3-8f7c00adeb1b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>cc4ecb66-3cb6-49d3-b923-f45885ee6bf7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Step Definition/feature_accept_bid/ACB001 - Accept bid</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>aa325f37-f765-4544-95f7-64a79d9d4517</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>14100b09-7f29-415f-bca0-b78086d48c1f</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
