<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>feature_login</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>249e598b-9c47-4c24-bcab-3bab28a551f1</testSuiteGuid>
   <testCaseLink>
      <guid>25393d70-3de6-4088-a2b6-badba026e9da</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Step Definition/feature_login/LGI001 - User want to login using correct credential</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ec3dadec-596d-46a5-b7db-3165f14f9c8c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a98ab0d5-1c55-4f72-92d4-611f228c9214</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4cd18f9f-4b7f-41bc-b7b9-96003760f5b8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Step Definition/feature_login/LGI002 - User want to login by not filling all field</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>011d0145-d8f4-41ba-a50f-62f45cee5189</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Step Definition/feature_login/LGI003 - User want to login using incorrect email credential</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a065b57a-7add-4699-bb60-e744a1f14e26</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e95976de-34d5-4fe7-9fb3-52680b8be775</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d770e2fc-1ece-4140-a833-74b3ad49950e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Step Definition/feature_login/LGI004 - User want to login using incorrect password credential</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d0bc16bd-c1f9-41c7-86ee-a9f032dc2583</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>34a7a3ef-c37a-482c-bbf2-0e9cc16604f7</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f0cbf1d1-609c-442a-a4dc-f90e87ef3746</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Step Definition/feature_login/LGI005 - User input incorrect email format on email textfield</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>87c261ec-af7d-4d77-8cef-625e7a23b153</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5ffa02c2-156b-4a31-aa5a-ddd8b6802b93</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
